language: python
if: branch = master
python: 3.6
services:
    - docker

before_script:
    # dependencies
    - wget https://github.com/riotkit-org/ci-utils/archive/v2.0.0.zip -O /tmp/ci-utils.zip
    - curl "https://raw.githubusercontent.com/riotkit-org/ci-utils/master/ci-integration/travis.sh" -s | bash

    # activate ARM builds on travis
    - /opt/riotkit/utils/bin/setup-travis-arm-builds

    # authorization
    - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$QUAY_PASSWORD" | sudo docker login -u "$QUAY_USERNAME" --password-stdin quay.io

jobs:
  include:
    - stage: Build recent x86_64 image
      script: make build_recent ARCH=x86_64 PUSH=true

    - stage: Build recent ARM image
      script: make build_recent ARCH=arm PUSH=true
